# Generated by Django 3.2.6 on 2021-08-18 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='markingcode',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='markingcode',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codes.product', verbose_name='Товар'),
        ),
    ]
